// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: pb/chat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	IdentityKey    []byte                 `protobuf:"bytes,2,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	VerifyingKey   []byte                 `protobuf:"bytes,3,opt,name=verifying_key,json=verifyingKey,proto3" json:"verifying_key,omitempty"`
	SignedPrekey   *SignedPrekey          `protobuf:"bytes,4,opt,name=signed_prekey,json=signedPrekey,proto3" json:"signed_prekey,omitempty"`
	OneTimePrekeys []*SignedPrekey        `protobuf:"bytes,5,rep,name=one_time_prekeys,json=oneTimePrekeys,proto3" json:"one_time_prekeys,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pb_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *RegisterRequest) GetVerifyingKey() []byte {
	if x != nil {
		return x.VerifyingKey
	}
	return nil
}

func (x *RegisterRequest) GetSignedPrekey() *SignedPrekey {
	if x != nil {
		return x.SignedPrekey
	}
	return nil
}

func (x *RegisterRequest) GetOneTimePrekeys() []*SignedPrekey {
	if x != nil {
		return x.OneTimePrekeys
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pb_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SignedPrekey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPrekey) Reset() {
	*x = SignedPrekey{}
	mi := &file_pb_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPrekey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPrekey) ProtoMessage() {}

func (x *SignedPrekey) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPrekey.ProtoReflect.Descriptor instead.
func (*SignedPrekey) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SignedPrekey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignedPrekey) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPrekey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UploadOTPsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	OneTimePrekeys []*SignedPrekey        `protobuf:"bytes,2,rep,name=one_time_prekeys,json=oneTimePrekeys,proto3" json:"one_time_prekeys,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadOTPsRequest) Reset() {
	*x = UploadOTPsRequest{}
	mi := &file_pb_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadOTPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadOTPsRequest) ProtoMessage() {}

func (x *UploadOTPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadOTPsRequest.ProtoReflect.Descriptor instead.
func (*UploadOTPsRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{3}
}

func (x *UploadOTPsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UploadOTPsRequest) GetOneTimePrekeys() []*SignedPrekey {
	if x != nil {
		return x.OneTimePrekeys
	}
	return nil
}

type UploadOTPsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadedCount int32                  `protobuf:"varint,1,opt,name=uploaded_count,json=uploadedCount,proto3" json:"uploaded_count,omitempty"`
	TotalOtps     int32                  `protobuf:"varint,2,opt,name=total_otps,json=totalOtps,proto3" json:"total_otps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadOTPsResponse) Reset() {
	*x = UploadOTPsResponse{}
	mi := &file_pb_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadOTPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadOTPsResponse) ProtoMessage() {}

func (x *UploadOTPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadOTPsResponse.ProtoReflect.Descriptor instead.
func (*UploadOTPsResponse) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{4}
}

func (x *UploadOTPsResponse) GetUploadedCount() int32 {
	if x != nil {
		return x.UploadedCount
	}
	return 0
}

func (x *UploadOTPsResponse) GetTotalOtps() int32 {
	if x != nil {
		return x.TotalOtps
	}
	return 0
}

type FetchBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBundleRequest) Reset() {
	*x = FetchBundleRequest{}
	mi := &file_pb_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBundleRequest) ProtoMessage() {}

func (x *FetchBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBundleRequest.ProtoReflect.Descriptor instead.
func (*FetchBundleRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{5}
}

func (x *FetchBundleRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type FetchBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bundle        *PrekeyBundle          `protobuf:"bytes,2,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBundleResponse) Reset() {
	*x = FetchBundleResponse{}
	mi := &file_pb_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBundleResponse) ProtoMessage() {}

func (x *FetchBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBundleResponse.ProtoReflect.Descriptor instead.
func (*FetchBundleResponse) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{6}
}

func (x *FetchBundleResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FetchBundleResponse) GetBundle() *PrekeyBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type PrekeyBundle struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey     []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	SignedPrekey    []byte                 `protobuf:"bytes,2,opt,name=signed_prekey,json=signedPrekey,proto3" json:"signed_prekey,omitempty"`
	PrekeySignature []byte                 `protobuf:"bytes,3,opt,name=prekey_signature,json=prekeySignature,proto3" json:"prekey_signature,omitempty"`
	OneTimePrekey   []byte                 `protobuf:"bytes,4,opt,name=one_time_prekey,json=oneTimePrekey,proto3,oneof" json:"one_time_prekey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrekeyBundle) Reset() {
	*x = PrekeyBundle{}
	mi := &file_pb_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrekeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrekeyBundle) ProtoMessage() {}

func (x *PrekeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrekeyBundle.ProtoReflect.Descriptor instead.
func (*PrekeyBundle) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{7}
}

func (x *PrekeyBundle) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *PrekeyBundle) GetSignedPrekey() []byte {
	if x != nil {
		return x.SignedPrekey
	}
	return nil
}

func (x *PrekeyBundle) GetPrekeySignature() []byte {
	if x != nil {
		return x.PrekeySignature
	}
	return nil
}

func (x *PrekeyBundle) GetOneTimePrekey() []byte {
	if x != nil {
		return x.OneTimePrekey
	}
	return nil
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ClientMessage_Join
	//	*ClientMessage_KeyExchange
	//	*ClientMessage_EncryptedMessage
	//	*ClientMessage_Heartbeat
	MessageType   isClientMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_pb_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ClientMessage) GetMessageType() isClientMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ClientMessage) GetJoin() *JoinRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ClientMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientMessage) GetKeyExchange() *KeyExchangeMessage {
	if x != nil {
		if x, ok := x.MessageType.(*ClientMessage_KeyExchange); ok {
			return x.KeyExchange
		}
	}
	return nil
}

func (x *ClientMessage) GetEncryptedMessage() *EncryptedMessage {
	if x != nil {
		if x, ok := x.MessageType.(*ClientMessage_EncryptedMessage); ok {
			return x.EncryptedMessage
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *HeartbeatMessage {
	if x != nil {
		if x, ok := x.MessageType.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isClientMessage_MessageType interface {
	isClientMessage_MessageType()
}

type ClientMessage_Join struct {
	Join *JoinRequest `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientMessage_KeyExchange struct {
	KeyExchange *KeyExchangeMessage `protobuf:"bytes,2,opt,name=key_exchange,json=keyExchange,proto3,oneof"`
}

type ClientMessage_EncryptedMessage struct {
	EncryptedMessage *EncryptedMessage `protobuf:"bytes,3,opt,name=encrypted_message,json=encryptedMessage,proto3,oneof"`
}

type ClientMessage_Heartbeat struct {
	Heartbeat *HeartbeatMessage `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*ClientMessage_Join) isClientMessage_MessageType() {}

func (*ClientMessage_KeyExchange) isClientMessage_MessageType() {}

func (*ClientMessage_EncryptedMessage) isClientMessage_MessageType() {}

func (*ClientMessage_Heartbeat) isClientMessage_MessageType() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ServerMessage_JoinResponse
	//	*ServerMessage_KeyExchange
	//	*ServerMessage_EncryptedMessage
	//	*ServerMessage_Heartbeat
	MessageType   isServerMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pb_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ServerMessage) GetMessageType() isServerMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ServerMessage) GetJoinResponse() *JoinResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ServerMessage_JoinResponse); ok {
			return x.JoinResponse
		}
	}
	return nil
}

func (x *ServerMessage) GetKeyExchange() *KeyExchangeMessage {
	if x != nil {
		if x, ok := x.MessageType.(*ServerMessage_KeyExchange); ok {
			return x.KeyExchange
		}
	}
	return nil
}

func (x *ServerMessage) GetEncryptedMessage() *EncryptedMessage {
	if x != nil {
		if x, ok := x.MessageType.(*ServerMessage_EncryptedMessage); ok {
			return x.EncryptedMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetHeartbeat() *HeartbeatMessage {
	if x != nil {
		if x, ok := x.MessageType.(*ServerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isServerMessage_MessageType interface {
	isServerMessage_MessageType()
}

type ServerMessage_JoinResponse struct {
	JoinResponse *JoinResponse `protobuf:"bytes,1,opt,name=join_response,json=joinResponse,proto3,oneof"`
}

type ServerMessage_KeyExchange struct {
	KeyExchange *KeyExchangeMessage `protobuf:"bytes,2,opt,name=key_exchange,json=keyExchange,proto3,oneof"`
}

type ServerMessage_EncryptedMessage struct {
	EncryptedMessage *EncryptedMessage `protobuf:"bytes,3,opt,name=encrypted_message,json=encryptedMessage,proto3,oneof"`
}

type ServerMessage_Heartbeat struct {
	Heartbeat *HeartbeatMessage `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*ServerMessage_JoinResponse) isServerMessage_MessageType() {}

func (*ServerMessage_KeyExchange) isServerMessage_MessageType() {}

func (*ServerMessage_EncryptedMessage) isServerMessage_MessageType() {}

func (*ServerMessage_Heartbeat) isServerMessage_MessageType() {}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_pb_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{10}
}

func (x *JoinRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_pb_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{11}
}

func (x *JoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type KeyExchangeMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId     string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	InitialMessage *InitialMessage        `protobuf:"bytes,3,opt,name=initial_message,json=initialMessage,proto3" json:"initial_message,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyExchangeMessage) Reset() {
	*x = KeyExchangeMessage{}
	mi := &file_pb_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeMessage) ProtoMessage() {}

func (x *KeyExchangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeMessage.ProtoReflect.Descriptor instead.
func (*KeyExchangeMessage) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{12}
}

func (x *KeyExchangeMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *KeyExchangeMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *KeyExchangeMessage) GetInitialMessage() *InitialMessage {
	if x != nil {
		return x.InitialMessage
	}
	return nil
}

func (x *KeyExchangeMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type InitialMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey   []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	EphemeralKey  []byte                 `protobuf:"bytes,2,opt,name=ephemeral_key,json=ephemeralKey,proto3" json:"ephemeral_key,omitempty"`
	SignedPrekey  []byte                 `protobuf:"bytes,3,opt,name=signed_prekey,json=signedPrekey,proto3" json:"signed_prekey,omitempty"`
	OneTimePrekey []byte                 `protobuf:"bytes,4,opt,name=one_time_prekey,json=oneTimePrekey,proto3,oneof" json:"one_time_prekey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialMessage) Reset() {
	*x = InitialMessage{}
	mi := &file_pb_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialMessage) ProtoMessage() {}

func (x *InitialMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialMessage.ProtoReflect.Descriptor instead.
func (*InitialMessage) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{13}
}

func (x *InitialMessage) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *InitialMessage) GetEphemeralKey() []byte {
	if x != nil {
		return x.EphemeralKey
	}
	return nil
}

func (x *InitialMessage) GetSignedPrekey() []byte {
	if x != nil {
		return x.SignedPrekey
	}
	return nil
}

func (x *InitialMessage) GetOneTimePrekey() []byte {
	if x != nil {
		return x.OneTimePrekey
	}
	return nil
}

type EncryptedMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId     string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	RatchetMessage *RatchetMessage        `protobuf:"bytes,3,opt,name=ratchet_message,json=ratchetMessage,proto3" json:"ratchet_message,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EncryptedMessage) Reset() {
	*x = EncryptedMessage{}
	mi := &file_pb_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessage) ProtoMessage() {}

func (x *EncryptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessage.ProtoReflect.Descriptor instead.
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{14}
}

func (x *EncryptedMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *EncryptedMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *EncryptedMessage) GetRatchetMessage() *RatchetMessage {
	if x != nil {
		return x.RatchetMessage
	}
	return nil
}

func (x *EncryptedMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RatchetMessage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PreviousChainLength int32                  `protobuf:"varint,2,opt,name=previous_chain_length,json=previousChainLength,proto3" json:"previous_chain_length,omitempty"`
	MessageNumber       int32                  `protobuf:"varint,3,opt,name=message_number,json=messageNumber,proto3" json:"message_number,omitempty"`
	Ciphertext          []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RatchetMessage) Reset() {
	*x = RatchetMessage{}
	mi := &file_pb_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatchetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatchetMessage) ProtoMessage() {}

func (x *RatchetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatchetMessage.ProtoReflect.Descriptor instead.
func (*RatchetMessage) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{15}
}

func (x *RatchetMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RatchetMessage) GetPreviousChainLength() int32 {
	if x != nil {
		return x.PreviousChainLength
	}
	return 0
}

func (x *RatchetMessage) GetMessageNumber() int32 {
	if x != nil {
		return x.MessageNumber
	}
	return 0
}

func (x *RatchetMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_pb_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UserRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	IdentityKey   []byte                 `protobuf:"bytes,2,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	VerifyingKey  []byte                 `protobuf:"bytes,3,opt,name=verifying_key,json=verifyingKey,proto3" json:"verifying_key,omitempty"`
	SignedPrekey  *SignedPrekey          `protobuf:"bytes,4,opt,name=signed_prekey,json=signedPrekey,proto3" json:"signed_prekey,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRecord) Reset() {
	*x = UserRecord{}
	mi := &file_pb_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRecord) ProtoMessage() {}

func (x *UserRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRecord.ProtoReflect.Descriptor instead.
func (*UserRecord) Descriptor() ([]byte, []int) {
	return file_pb_chat_proto_rawDescGZIP(), []int{17}
}

func (x *UserRecord) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserRecord) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *UserRecord) GetVerifyingKey() []byte {
	if x != nil {
		return x.VerifyingKey
	}
	return nil
}

func (x *UserRecord) GetSignedPrekey() *SignedPrekey {
	if x != nil {
		return x.SignedPrekey
	}
	return nil
}

func (x *UserRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserRecord) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

var File_pb_chat_proto protoreflect.FileDescriptor

const file_pb_chat_proto_rawDesc = "" +
	"\n" +
	"\rpb/chat.proto\x12\x03pch\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fidentity_key\x18\x02 \x01(\fR\videntityKey\x12#\n" +
	"\rverifying_key\x18\x03 \x01(\fR\fverifyingKey\x126\n" +
	"\rsigned_prekey\x18\x04 \x01(\v2\x11.pch.SignedPrekeyR\fsignedPrekey\x12;\n" +
	"\x10one_time_prekeys\x18\x05 \x03(\v2\x11.pch.SignedPrekeyR\x0eoneTimePrekeys\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x86\x01\n" +
	"\fSignedPrekey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"l\n" +
	"\x11UploadOTPsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12;\n" +
	"\x10one_time_prekeys\x18\x02 \x03(\v2\x11.pch.SignedPrekeyR\x0eoneTimePrekeys\"Z\n" +
	"\x12UploadOTPsResponse\x12%\n" +
	"\x0euploaded_count\x18\x01 \x01(\x05R\ruploadedCount\x12\x1d\n" +
	"\n" +
	"total_otps\x18\x02 \x01(\x05R\ttotalOtps\"0\n" +
	"\x12FetchBundleRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\\\n" +
	"\x13FetchBundleResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12)\n" +
	"\x06bundle\x18\x02 \x01(\v2\x11.pch.PrekeyBundleR\x06bundle\"\xc2\x01\n" +
	"\fPrekeyBundle\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12#\n" +
	"\rsigned_prekey\x18\x02 \x01(\fR\fsignedPrekey\x12)\n" +
	"\x10prekey_signature\x18\x03 \x01(\fR\x0fprekeySignature\x12+\n" +
	"\x0fone_time_prekey\x18\x04 \x01(\fH\x00R\roneTimePrekey\x88\x01\x01B\x12\n" +
	"\x10_one_time_prekey\"\x82\x02\n" +
	"\rClientMessage\x12&\n" +
	"\x04join\x18\x01 \x01(\v2\x10.pch.JoinRequestH\x00R\x04join\x12<\n" +
	"\fkey_exchange\x18\x02 \x01(\v2\x17.pch.KeyExchangeMessageH\x00R\vkeyExchange\x12D\n" +
	"\x11encrypted_message\x18\x03 \x01(\v2\x15.pch.EncryptedMessageH\x00R\x10encryptedMessage\x125\n" +
	"\theartbeat\x18\x04 \x01(\v2\x15.pch.HeartbeatMessageH\x00R\theartbeatB\x0e\n" +
	"\fmessage_type\"\x94\x02\n" +
	"\rServerMessage\x128\n" +
	"\rjoin_response\x18\x01 \x01(\v2\x11.pch.JoinResponseH\x00R\fjoinResponse\x12<\n" +
	"\fkey_exchange\x18\x02 \x01(\v2\x17.pch.KeyExchangeMessageH\x00R\vkeyExchange\x12D\n" +
	"\x11encrypted_message\x18\x03 \x01(\v2\x15.pch.EncryptedMessageH\x00R\x10encryptedMessage\x125\n" +
	"\theartbeat\x18\x04 \x01(\v2\x15.pch.HeartbeatMessageH\x00R\theartbeatB\x0e\n" +
	"\fmessage_type\")\n" +
	"\vJoinRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"b\n" +
	"\fJoinResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xca\x01\n" +
	"\x12KeyExchangeMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12<\n" +
	"\x0finitial_message\x18\x03 \x01(\v2\x13.pch.InitialMessageR\x0einitialMessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xbe\x01\n" +
	"\x0eInitialMessage\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12#\n" +
	"\rephemeral_key\x18\x02 \x01(\fR\fephemeralKey\x12#\n" +
	"\rsigned_prekey\x18\x03 \x01(\fR\fsignedPrekey\x12+\n" +
	"\x0fone_time_prekey\x18\x04 \x01(\fH\x00R\roneTimePrekey\x88\x01\x01B\x12\n" +
	"\x10_one_time_prekey\"\xc8\x01\n" +
	"\x10EncryptedMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12<\n" +
	"\x0fratchet_message\x18\x03 \x01(\v2\x13.pch.RatchetMessageR\x0eratchetMessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xaa\x01\n" +
	"\x0eRatchetMessage\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x122\n" +
	"\x15previous_chain_length\x18\x02 \x01(\x05R\x13previousChainLength\x12%\n" +
	"\x0emessage_number\x18\x03 \x01(\x05R\rmessageNumber\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\"L\n" +
	"\x10HeartbeatMessage\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9c\x02\n" +
	"\n" +
	"UserRecord\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fidentity_key\x18\x02 \x01(\fR\videntityKey\x12#\n" +
	"\rverifying_key\x18\x03 \x01(\fR\fverifyingKey\x126\n" +
	"\rsigned_prekey\x18\x04 \x01(\v2\x11.pch.SignedPrekeyR\fsignedPrekey\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen2\x84\x02\n" +
	"\vChatService\x127\n" +
	"\bRegister\x12\x14.pch.RegisterRequest\x1a\x15.pch.RegisterResponse\x12=\n" +
	"\n" +
	"UploadOTPs\x12\x16.pch.UploadOTPsRequest\x1a\x17.pch.UploadOTPsResponse\x12@\n" +
	"\vFetchBundle\x12\x17.pch.FetchBundleRequest\x1a\x18.pch.FetchBundleResponse\x12;\n" +
	"\rMessageStream\x12\x12.pch.ClientMessage\x1a\x12.pch.ServerMessage(\x010\x01B\x1cZ\x1agithub.com/nireo/pch/protob\x06proto3"

var (
	file_pb_chat_proto_rawDescOnce sync.Once
	file_pb_chat_proto_rawDescData []byte
)

func file_pb_chat_proto_rawDescGZIP() []byte {
	file_pb_chat_proto_rawDescOnce.Do(func() {
		file_pb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_chat_proto_rawDesc), len(file_pb_chat_proto_rawDesc)))
	})
	return file_pb_chat_proto_rawDescData
}

var file_pb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pb_chat_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: pch.RegisterRequest
	(*RegisterResponse)(nil),      // 1: pch.RegisterResponse
	(*SignedPrekey)(nil),          // 2: pch.SignedPrekey
	(*UploadOTPsRequest)(nil),     // 3: pch.UploadOTPsRequest
	(*UploadOTPsResponse)(nil),    // 4: pch.UploadOTPsResponse
	(*FetchBundleRequest)(nil),    // 5: pch.FetchBundleRequest
	(*FetchBundleResponse)(nil),   // 6: pch.FetchBundleResponse
	(*PrekeyBundle)(nil),          // 7: pch.PrekeyBundle
	(*ClientMessage)(nil),         // 8: pch.ClientMessage
	(*ServerMessage)(nil),         // 9: pch.ServerMessage
	(*JoinRequest)(nil),           // 10: pch.JoinRequest
	(*JoinResponse)(nil),          // 11: pch.JoinResponse
	(*KeyExchangeMessage)(nil),    // 12: pch.KeyExchangeMessage
	(*InitialMessage)(nil),        // 13: pch.InitialMessage
	(*EncryptedMessage)(nil),      // 14: pch.EncryptedMessage
	(*RatchetMessage)(nil),        // 15: pch.RatchetMessage
	(*HeartbeatMessage)(nil),      // 16: pch.HeartbeatMessage
	(*UserRecord)(nil),            // 17: pch.UserRecord
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_pb_chat_proto_depIdxs = []int32{
	2,  // 0: pch.RegisterRequest.signed_prekey:type_name -> pch.SignedPrekey
	2,  // 1: pch.RegisterRequest.one_time_prekeys:type_name -> pch.SignedPrekey
	18, // 2: pch.SignedPrekey.created_at:type_name -> google.protobuf.Timestamp
	2,  // 3: pch.UploadOTPsRequest.one_time_prekeys:type_name -> pch.SignedPrekey
	7,  // 4: pch.FetchBundleResponse.bundle:type_name -> pch.PrekeyBundle
	10, // 5: pch.ClientMessage.join:type_name -> pch.JoinRequest
	12, // 6: pch.ClientMessage.key_exchange:type_name -> pch.KeyExchangeMessage
	14, // 7: pch.ClientMessage.encrypted_message:type_name -> pch.EncryptedMessage
	16, // 8: pch.ClientMessage.heartbeat:type_name -> pch.HeartbeatMessage
	11, // 9: pch.ServerMessage.join_response:type_name -> pch.JoinResponse
	12, // 10: pch.ServerMessage.key_exchange:type_name -> pch.KeyExchangeMessage
	14, // 11: pch.ServerMessage.encrypted_message:type_name -> pch.EncryptedMessage
	16, // 12: pch.ServerMessage.heartbeat:type_name -> pch.HeartbeatMessage
	18, // 13: pch.JoinResponse.timestamp:type_name -> google.protobuf.Timestamp
	13, // 14: pch.KeyExchangeMessage.initial_message:type_name -> pch.InitialMessage
	18, // 15: pch.KeyExchangeMessage.timestamp:type_name -> google.protobuf.Timestamp
	15, // 16: pch.EncryptedMessage.ratchet_message:type_name -> pch.RatchetMessage
	18, // 17: pch.EncryptedMessage.timestamp:type_name -> google.protobuf.Timestamp
	18, // 18: pch.HeartbeatMessage.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 19: pch.UserRecord.signed_prekey:type_name -> pch.SignedPrekey
	18, // 20: pch.UserRecord.created_at:type_name -> google.protobuf.Timestamp
	18, // 21: pch.UserRecord.last_seen:type_name -> google.protobuf.Timestamp
	0,  // 22: pch.ChatService.Register:input_type -> pch.RegisterRequest
	3,  // 23: pch.ChatService.UploadOTPs:input_type -> pch.UploadOTPsRequest
	5,  // 24: pch.ChatService.FetchBundle:input_type -> pch.FetchBundleRequest
	8,  // 25: pch.ChatService.MessageStream:input_type -> pch.ClientMessage
	1,  // 26: pch.ChatService.Register:output_type -> pch.RegisterResponse
	4,  // 27: pch.ChatService.UploadOTPs:output_type -> pch.UploadOTPsResponse
	6,  // 28: pch.ChatService.FetchBundle:output_type -> pch.FetchBundleResponse
	9,  // 29: pch.ChatService.MessageStream:output_type -> pch.ServerMessage
	26, // [26:30] is the sub-list for method output_type
	22, // [22:26] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_pb_chat_proto_init() }
func file_pb_chat_proto_init() {
	if File_pb_chat_proto != nil {
		return
	}
	file_pb_chat_proto_msgTypes[7].OneofWrappers = []any{}
	file_pb_chat_proto_msgTypes[8].OneofWrappers = []any{
		(*ClientMessage_Join)(nil),
		(*ClientMessage_KeyExchange)(nil),
		(*ClientMessage_EncryptedMessage)(nil),
		(*ClientMessage_Heartbeat)(nil),
	}
	file_pb_chat_proto_msgTypes[9].OneofWrappers = []any{
		(*ServerMessage_JoinResponse)(nil),
		(*ServerMessage_KeyExchange)(nil),
		(*ServerMessage_EncryptedMessage)(nil),
		(*ServerMessage_Heartbeat)(nil),
	}
	file_pb_chat_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_chat_proto_rawDesc), len(file_pb_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_chat_proto_goTypes,
		DependencyIndexes: file_pb_chat_proto_depIdxs,
		MessageInfos:      file_pb_chat_proto_msgTypes,
	}.Build()
	File_pb_chat_proto = out.File
	file_pb_chat_proto_goTypes = nil
	file_pb_chat_proto_depIdxs = nil
}
